In [1]:
import numpy as np
import pandas as pd

In [4]:
unames = ['userid','gender','age','occupation','zip']

users = pd.read_table('ml-1m/users.dat',sep='::',header=None,names=unames)

c:\users\tang\envs\mz_pandas\lib\site-packages\ipykernel\__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()

In [6]:
users.head()

   userid gender  age  occupation    zip
0       1      F    1          10  48067
1       2      M   56          16  70072
2       3      M   25          15  55117
3       4      M   45           7  02460
4       5      M   25          20  55455

In [7]:
movies_names = ['movieid','title','genres']
movies = pd.read_table('ml-1m/movies.dat',sep='::',header=None,names=movies_names)

rating_names = ['userid','movieid','rating','timestamp']
ratings = pd.read_table('ml-1m/ratings.dat',sep='::',header=None,names=rating_names)

c:\users\tang\envs\mz_pandas\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app
c:\users\tang\envs\mz_pandas\lib\site-packages\ipykernel\__main__.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [8]:
movies

,movieid,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [9]:
ratings.head()

   userid  movieid  rating  timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [11]:
data = pd.merge(pd.merge(users,ratings),movies)

In [12]:
data.head()

,userid,gender,age,occupation,zip,movieid,rating,timestamp,title,genres
0,1,F,1,10,48067,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,M,56,16,70072,1193,5,978298413,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,M,25,12,32793,1193,4,978220179,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,M,25,7,22903,1193,4,978199279,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,M,50,1,95350,1193,5,978158471,One Flew Over the Cuckoo's Nest (1975),Drama

In [14]:
data.to_csv('ml-1m/data.csv')

In [15]:
data.head(10)

,userid,gender,age,occupation,zip,movieid,rating,timestamp,title,genres
0,1,F,1,10,48067,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,M,56,16,70072,1193,5,978298413,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,M,25,12,32793,1193,4,978220179,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,M,25,7,22903,1193,4,978199279,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,M,50,1,95350,1193,5,978158471,One Flew Over the Cuckoo's Nest (1975),Drama
5,18,F,18,3,95825,1193,4,978156168,One Flew Over the Cuckoo's Nest (1975),Drama
6,19,M,1,10,48073,1193,5,982730936,One Flew Over the Cuckoo's Nest (1975),Drama
7,24,F,25,7,10023,1193,5,978136709,One Flew Over the Cuckoo's Nest (1975),Drama
8,28,F,25,1,14607,1193,3,978125194,One Flew Over the Cuckoo's Nest (1975),Drama
9,33,M,45,3,55421,1193,5,978557765,One Flew Over the Cuckoo's Nest (1975),Drama

In [17]:
data[data.userid==1]

,userid,gender,age,occupation,zip,movieid,rating,timestamp,title,genres
0,1,F,1,10,48067,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1725,1,F,1,10,48067,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical
2250,1,F,1,10,48067,914,3,978301968,My Fair Lady (1964),Musical|Romance
2886,1,F,1,10,48067,3408,4,978300275,Erin Brockovich (2000),Drama
4201,1,F,1,10,48067,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy
5904,1,F,1,10,48067,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance
8222,1,F,1,10,48067,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama
8926,1,F,1,10,48067,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama
10278,1,F,1,10,48067,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical
11041,1,F,1,10,48067,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical
12759,1,F,1,10,48067,595,5,978824268,Beauty and the Beast (1991),Animation|Children's|Musical
13819,1,F,1,10,48067,938,4,978301752,Gigi (1958),Musical
14006,1,F,1,10,48067,2398,4,978302281,Miracle on 34th Street (1947),Drama
14386,1,F,1,10,48067,2918,4,978302124,Ferris Bueller's Day Off (1986),Comedy
15859,1,F,1,10,48067,1035,5,978301753,"Sound of Music, The (1965)",Musical
16741,1,F,1,10,48067,2791,4,978302188,Airplane! (1980),Comedy
18472,1,F,1,10,48067,2687,3,978824268,Tarzan (1999),Animation|Children's
18914,1,F,1,10,48067,2018,4,978301777,Bambi (1942),Animation|Children's
19503,1,F,1,10,48067,3105,5,978301713,Awakenings (1990),Drama
20183,1,F,1,10,48067,2797,4,978302039,Big (1988),Comedy|Fantasy
21674,1,F,1,10,48067,2321,3,978302205,Pleasantville (1998),Comedy
22832,1,F,1,10,48067,720,3,978300760,Wallace & Gromit: The Best of Aardman Animatio...,Animation
23270,1,F,1,10,48067,1270,5,978300055,Back to the Future (1985),Comedy|Sci-Fi
25853,1,F,1,10,48067,527,5,978824195,Schindler's List (1993),Drama|War
28157,1,F,1,10,48067,2340,3,978300103,Meet Joe Black (1998),Romance
28501,1,F,1,10,48067,48,5,978824351,Pocahontas (1995),Animation|Children's|Musical|Romance
28883,1,F,1,10,48067,1097,4,978301953,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi
31152,1,F,1,10,48067,1721,4,978300055,Titanic (1997),Drama|Romance
32698,1,F,1,10,48067,1545,4,978824139,Ponette (1996),Drama
32771,1,F,1,10,48067,745,3,978824268,"Close Shave, A (1995)",Animation|Comedy|Thriller
33428,1,F,1,10,48067,2294,4,978824291,Antz (1998),Animation|Children's
34073,1,F,1,10,48067,3186,4,978300019,"Girl, Interrupted (1999)",Drama
34504,1,F,1,10,48067,1566,4,978824330,Hercules (1997),Adventure|Animation|Children's|Comedy|Musical
34973,1,F,1,10,48067,588,4,978824268,Aladdin (1992),Animation|Children's|Comedy|Musical
36324,1,F,1,10,48067,1907,4,978824330,Mulan (1998),Animation|Children's
36814,1,F,1,10,48067,783,4,978824291,"Hunchback of Notre Dame, The (1996)",Animation|Children's|Musical
37204,1,F,1,10,48067,1836,5,978300172,"Last Days of Disco, The (1998)",Drama
37339,1,F,1,10,48067,1022,5,978300055,Cinderella (1950),Animation|Children's|Musical
37916,1,F,1,10,48067,2762,4,978302091,"Sixth Sense, The (1999)",Thriller
40375,1,F,1,10,48067,150,5,978301777,Apollo 13 (1995),Drama
41626,1,F,1,10,48067,1,5,978824268,Toy Story (1995),Animation|Children's|Comedy
43703,1,F,1,10,48067,1961,5,978301590,Rain Man (1988),Drama
45033,1,F,1,10,48067,1962,4,978301753,Driving Miss Daisy (1989),Drama
45685,1,F,1,10,48067,2692,4,978301570,Run Lola Run (Lola rennt) (1998),Action|Crime|Romance
46757,1,F,1,10,48067,260,4,978300760,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi
49748,1,F,1,10,48067,1028,5,978301777,Mary Poppins (1964),Children's|Comedy|Musical
50759,1,F,1,10,48067,1029,5,978302205,Dumbo (1941),Animation|Children's|Musical
51327,1,F,1,10,48067,1207,4,978300719,To Kill a Mockingbird (1962),Drama
52255,1,F,1,10,48067,2028,5,978301619,Saving Private Ryan (1998),Action|Drama|War
54908,1,F,1,10,48067,531,4,978302149,"Secret Garden, The (1993)",Children's|Drama
55246,1,F,1,10,48067,3114,4,978302174,Toy Story 2 (1999),Animation|Children's|Comedy
56831,1,F,1,10,48067,608,4,978301398,Fargo (1996),Crime|Drama|Thriller
59344,1,F,1,10,48067,1246,4,978302091,Dead Poets Society (1989),Drama